services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: imgq
      POSTGRES_USER: imgq_user
      POSTGRES_PASSWORD: imgq_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

volumes:
  db_data:

# To shut down the services, run:
# docker-compose down